import type { Metadata } from "next";
import styles from "./layout.module.scss";
import Link from "next/link";


export const metadata: Metadata = {
  title: "UI",
  description: "Generated by create next app",
};

export default function UiLayout({ children }: { children: React.ReactNode }) {
  return (
    <div className={styles.layout}>
      <div className={styles.menu}>

        <Link href={'/ui/modal'}>Modal</Link>
      </div>

      {children}
    </div>
  );
}
